version: 2

builds:
  - main: ./cmd/pem2jks
    binary: pem2jks
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.BuildDate={{.Date}}

archives:
  - formats: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}
    artifacts: checksum
    output: true

docker_signs:
  - cmd: cosign
    args:
      - sign
      - --yes
      - ${artifact}
    output: true

sboms:
  - artifacts: binary
    cmd: syft
    documents:
      - "{{ .ArtifactName }}.sbom.spdx.json"

dockers_v2:
  - images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/pem2jks"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - LICENSE.txt

release:
  prerelease: auto

changelog:
  use: github-native
