version: 2

builds:
  - main: ./cmd/pem2jks
    binary: pem2jks
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.BuildDate={{.Date}}

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}
    artifacts: checksum
    output: true

sboms:
  - artifacts: binary
    cmd: syft
    documents:
      - "${artifact}.sbom.spdx.json"

release:
  prerelease: auto

changelog:
  use: github-native
